### ISSUE TITLE
求助：只能从标点符号处开始搜索

### ISSUE THREAD

**Issue by yefeiyu** [codepiano/lunr.js#3]
譬如“使用jeky-lunr-js-search进行搜索”这句，搜“使用”就可以，搜“搜索”就不行。
我使用的是https://github.com/slashdotdash/jekyll-lunr-js-search
直接用您的文件替换了jekyll-lunr-js-search需要的lunr.js和lunr.min.js，出现了上述情况。
我是否还有没拷贝的文件？

**Comment by codepiano** [comment]
没了，用也是用这两个文件。
我这个必须提前用命令行建索引文件，网页引用索引文件，没有索引文件的话不能直接在浏览器里面搜索。

**Comment by yefeiyu** [comment]
感谢您这么快回复了。
我这几天是安装了https://github.com/slashdotdash/jekyll-lunr-js-search，又为了中文搜索想安装https://github.com/MihaiValentin/lunr-languages中的lunr.jp.js，但是弄不明白怎么在jekyll-lunr-js-search中用lunr-languages。
只好将您的lunr.js版本替换到jekyll-lunr-js-search中，可以中文搜索了，但出现上述问题。
在lunr-languages中也有和您的lunr.js同样的

``` ruby
var idx = lunr(function () {
    // use the language (de)
    this.use(lunr.de);
    // then, the normal lunr index initialization
    this.field('title', { boost: 10 });
    this.field('body');
});
```

实在不懂得怎么去用。
您的命令行，是否就是指这个？能否详细说说？
谢谢了。
（我主要是github博客使用想放个搜索的链接）

**Comment by codepiano** [comment]
你如果是纯静态的页面，需要先建一个索引文件，就像下面这个：http://www.frontendhandbook.com/search_index.json
你看一下你的索引文件正常不正常，如果搜不出来可能是索引文件的问题
